### ISSUE TITLE
Prohibido esto que acabas de hacer

### ISSUE THREAD

**Issue by gaal1le0** [ismabk/Landing-Travel#1]
https://github.com/ismabk/Landing-Travel/blob/e1a652af33b4bf004aa6ea38cbecb666998080ad/index.html#L11

Queda totalmente prohibido colocar codigo JS dentro del HTML. Debes crear un archivo que se llame `index.js` e incluirlo al final del body.

```js
<script src="index.js"></script>
```

Es muy importante que lo incluyas **al final del body**, más adelante entenderás por que.

**Comment by ismabk** [comment]
Separado del index.html el código js y subido todo a master

**Comment by gaal1le0** [comment]
Así si maestro :) 
PD: Que rapidez!!!
