### ISSUE TITLE
No sigues la estructura de archivos propuesta

### ISSUE THREAD

**Issue by gaal1le0** [ismabk/Landing-Travel#3]
https://github.com/ismabk/Landing-Travel/blob/d20e7ef5438dd031b8efe7f2c76127fc31868f87/index.html#L1

Recordad que ayer propuse una estructura de archivos que es de carácter obligatorio para todas las entregas incluida la entrega colaborativa, por lo que debes modificar la estructura a la comentada y por mi en cuanto referente a esto perfecto.

PD: He visto que habeís comentado y todo, eso está perfecto el único problema es la estructura.

**Comment by ismabk** [comment]
Creada y subida la estructura nueva
